# This file is automatically generated by pyo3_stub_gen

import builtins
import enum
import typing

import numpy as np

@typing.final
class AlignFrag:
    @property
    def frag_type(self) -> FragType: ...
    @frag_type.setter
    def frag_type(self, value: FragType) -> None: ...
    @property
    def sa_start(self) -> builtins.int: ...
    @property
    def sb_start(self) -> builtins.int: ...
    @property
    def len(self) -> builtins.int: ...

@typing.final
class Alignment:
    @property
    def align_frag(self) -> builtins.list[AlignFrag]: ...
    @property
    def frag_count(self) -> builtins.int: ...
    @property
    def score(self) -> builtins.int: ...

@typing.final
class FragType(enum.Enum):
    AGap = ...
    BGap = ...
    Match = ...

def global_align(
    seqa: bytes,
    seqb: bytes,
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
) -> Alignment: ...
def local_align(
    seqa: bytes,
    seqb: bytes,
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
) -> Alignment: ...
def local_global_align(
    seqa: bytes,
    seqb: bytes,
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
) -> Alignment: ...
def overlap_align(
    seqa: bytes,
    seqb: bytes,
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
) -> Alignment: ...
