# This file is automatically generated by pyo3_stub_gen

import builtins
import enum
import typing

import numpy as np

@typing.final
class Alignment:
    @property
    def fragments(self) -> builtins.list[AlignmentFragment]: ...
    @property
    def score(self) -> builtins.int: ...

@typing.final
class AlignmentFragment:
    @property
    def fragment_type(self) -> FragmentType: ...
    @fragment_type.setter
    def fragment_type(self, value: FragmentType) -> None: ...
    @property
    def sa_start(self) -> builtins.int: ...
    @property
    def sb_start(self) -> builtins.int: ...
    @property
    def len(self) -> builtins.int: ...

@typing.final
class FragmentType(enum.Enum):
    AGap = ...
    BGap = ...
    Match = ...

def global_align(
    seqa: bytes,
    seqb: bytes,
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
) -> Alignment: ...
def global_align_many(
    seqa: bytes,
    seqbs: typing.Sequence[bytes],
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
    num_threads: builtins.int | None = None,
) -> builtins.list[Alignment]: ...
def local_align(
    seqa: bytes,
    seqb: bytes,
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
) -> Alignment: ...
def local_align_many(
    seqa: bytes,
    seqbs: typing.Sequence[bytes],
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
    num_threads: builtins.int | None = None,
) -> builtins.list[Alignment]: ...
def local_global_align(
    seqa: bytes,
    seqb: bytes,
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
) -> Alignment: ...
def local_global_align_many(
    seqa: bytes,
    seqbs: typing.Sequence[bytes],
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
    num_threads: builtins.int | None = None,
) -> builtins.list[Alignment]: ...
def overlap_align(
    seqa: bytes,
    seqb: bytes,
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
) -> Alignment: ...
def overlap_align_many(
    seqa: bytes,
    seqbs: typing.Sequence[bytes],
    score_matrix: np.typing.NDArray[np.int32],
    gap_open: builtins.int,
    gap_extend: builtins.int,
    num_threads: builtins.int | None = None,
) -> builtins.list[Alignment]: ...
