version: 2

build:
  os: ubuntu-latest
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
